name: Docker Publish

on:
  push:
    branches:
      - main
      - develop
    tags:
      - 'v*'
      - 'V*'

jobs:
  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    if: startsWith(github.ref, 'refs/tags/v') || startsWith(github.ref, 'refs/tags/V')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies for auth
        working-directory: ./auth
        run: npm install

      - name: Generate INTERNAL_JWT_SECRET in .env files
        working-directory: ./auth
        run: npm run set-internal-token

      - name: Extract Tag Version
        id: extract_version
        run: |
          echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Validate Tag Format
        id: validate
        run: |
          TAG=${{ steps.extract_version.outputs.TAG_NAME }}
          if [[ ! "$TAG" =~ ^(v|V)?([0-9]+\.){2}[0-9]+(\.hf[0-9]+)?$ ]]; then
            echo "Invalid tag format: $TAG"
            exit 1
          fi
          echo "Valid tag: $TAG"

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Auth image
        uses: docker/build-push-action@v5
        with:
          context: ./auth
          file: ./auth/Dockerfile
          push: true
          tags: melquidocker/micro-servico-nest:auth-${{ steps.extract_version.outputs.TAG_NAME }}

      - name: Build and push Projects image
        uses: docker/build-push-action@v5
        with:
          context: ./projects-service
          file: ./projects-service/Dockerfile
          push: true
          tags: melquidocker/micro-servico-nest:projects-${{ steps.extract_version.outputs.TAG_NAME }}

      - name: Build and push Tasks image
        uses: docker/build-push-action@v5
        with:
          context: ./tasks-service
          file: ./tasks-service/Dockerfile
          push: true
          tags: melquidocker/micro-servico-nest:tasks-${{ steps.extract_version.outputs.TAG_NAME }}